language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - mysql -e 'create database budget_testing;'
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --database=testing

jobs:
  include:
    - stage: test
      name: "PHPUnit"
      script: vendor/bin/phpunit
    - stage: test
      name: "PHPCS"
      script: vendor/bin/phpcs
